In [1]:
import numpy as np


In [2]:
#Pass matrix
A = np.matrix([[0.25, 0.20, 0.1], [0.1, 0.25, 0.2],[0.1, 0.1, 0.25]])
#Goal vector
g = np.transpose(np.matrix([0.05, 0.15, 0.05]))

# Solution Using Linear Algebra

In [3]:
xT1 = np.linalg.solve(np.identity(3) - A,g)

print('Expected Threat')
print('Central, Box, Wing')
print(np.transpose(xT1))

Expected Threat
Central, Box, Wing
[[0.14991763 0.25205931 0.12026359]]


# Iterative Solution

In [4]:
xT2=np.zeros((3,1))
for t in range(10):
   print(np.matmul(A,xT2) + g)
   xT2 = np.matmul(A,xT2) + g

print('Expected Threat')
print('Central, Box, Wing')
print(np.transpose(xT2))

[[0.05]
 [0.15]
 [0.05]]
[[0.0975]
 [0.2025]
 [0.0825]]
[[0.123125]
 [0.226875]
 [0.100625]]
[[0.13621875]
 [0.23915625]
 [0.11015625]]
[[0.14290156]
 [0.24544219]
 [0.11507656]]
[[0.14632148]
 [0.24866602]
 [0.11760352]]
[[0.14807393]
 [0.25031936]
 [0.11889963]]
[[0.14897232]
 [0.25116716]
 [0.11956424]]
[[0.14943293]
 [0.25160187]
 [0.11990501]]
[[0.14966911]
 [0.25182476]
 [0.12007973]]
Expected Threat
Central, Box, Wing
[[0.14966911 0.25182476 0.12007973]]


# Monte Carlo Simulation

In [5]:
num_sims=3
xT3=np.zeros(3)

description = {0: 'Central', 1: 'Wing', 2: 'Box' }

for i in range(3):
    num_goals = 0

    print('---------------')
    print('Start from ' + description[i] )
    print('---------------')

    for n in range(num_sims):

        ballinplay=True
        #Initial state is i
        s = i
        describe_possession=''

        while ballinplay:
            r=np.random.rand()

            # Make commentary text
            describe_possession = describe_possession + ' - ' + description[s]


            #Cumulative sum of in play probabilities
            c_sum=np.cumsum(A[s,:])
            new_s = np.sum(r>c_sum)
            if new_s>2:
                #Ball is either goal or out of play
                ballinplay=False
                if r < g[s] + c_sum[0,2]:
                    #Its a goal!
                    num_goals = num_goals + 1
                    describe_possession = describe_possession + ' - Goal!'
                else:
                    describe_possession = describe_possession + ' - Out of play'
            s = new_s

        print(describe_possession)

    xT3[i] = num_goals/num_sims


print('\n\n---------------')
print('Expected Threat')
print('Central, Box, Wing')
print(xT3)

---------------
Start from Central
---------------
 - Central - Out of play
 - Central - Out of play
 - Central - Out of play
---------------
Start from Wing
---------------
 - Wing - Wing - Wing - Central - Central - Central - Out of play
 - Wing - Box - Central - Wing - Box - Box - Central - Out of play
 - Wing - Box - Box - Wing - Central - Central - Box - Out of play
---------------
Start from Box
---------------
 - Box - Central - Goal!
 - Box - Out of play
 - Box - Out of play


---------------
Expected Threat
Central, Box, Wing
[0.         0.         0.33333333]


**Expected Threat (xT)** for three pitch zones by simulating possessions.

Zones:
- `0 → Central`
- `1 → Wing`
- `2 → Box`


We simulate many possessions and estimate the **probability of scoring**.

`num_sims` = number of simulated possessions per zone  
`xT3` = stores xT values for each zone.

Example:  
If **1 goal occurs in 2 simulations**

xT = 1 / 2 = **0.5**

Each simulation starts from a zone.

The simulation then continues while the ball is in play.



At every step the code generates a random number:

`r = np.random.rand()`

Example:

`r = 0.63`

This random value determines what event happens next.



Matrix `A` contains the **passing probabilities between zones**.

Example (from Central):

Central → Central = 0.30  
Central → Wing = 0.40  
Central → Box = 0.20  

Total passing probability = **0.90**

Cumulative probabilities become:

`[0.30, 0.70, 0.90]`

Example:

If `r = 0.63`

0.30 < 0.63 < 0.70 → **ball moves to Wing**

Possession path becomes:

Central → Wing


If the random number is larger than the passing probability (here **> 0.90**), the possession ends.

Two possibilities:

Goal probability is stored in `g[s]`.

Example:

`g[Central] = 0.05`

Goal range:

0.90 → 0.95

If:

`r = 0.92` → **Goal**

If:

`r = 0.97` → **Out of play**

Example simulated possession:

Central → Wing → Box → Goal


After running the simulations:

`xT3[i] = num_goals / num_sims`

Example result:

Central: 1 goal in 10 simulations → xT = **0.10**  
Wing: 0 goals in 10 simulations → xT = **0.00**  
Box: 3 goals in 10 simulations → xT = **0.30**



Expected Threat measures:

xT(zone) = P(goal | possession starts in that zone)

By simulating many possessions, we estimate **how dangerous each area of the pitch is**.